spring.application.name=R_Petals
spring.profiles.active=local
spring.data.mongodb.uri =
jwt.secret =

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
.
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=25MB

# MSG91 -> dashboard.msg91.com -> API -> Auth Key
msg91.auth-key=
msg91.template-id=)
msg91.otp-variable-name=OTP